# Generated by Django 3.1.1 on 2020-10-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201017_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.CharField(default='username', max_length=64),
        ),
    ]
