# Generated by Django 3.1.1 on 2020-11-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201114_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='producturl',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
